notifications:
  email:
    recipients:
      - rr@ml.commit-email.info
language: ruby
before_install:
  - gem update bundler
script: bundle exec rake ${TARGET}
matrix:
  include:
  - rvm: 2.0.0
    env:
    - SPEC_OPTS="--require $PWD/spec/custom_formatter_for_rspec_2 --format CustomFormatterForRSpec2
      --backtrace"
    - TARGET="spec:rspec_2"
  - rvm: 2.0.0
    env:
    - SPEC_OPTS="--require $PWD/spec/custom_formatter_for_rspec_2 --format CustomFormatterForRSpec2
      --backtrace"
    - TARGET="spec:rspec_2_rails_4"
  - rvm: 2.0.0
    env:
    - TARGET="test"
  - rvm: 2.1
    env:
    - TARGET="test"
  - rvm: 2.2
    env:
    - TARGET="test"
  - rvm: 2.3.1
    env:
    - TARGET="test"
  - rvm: 2.4.0
    env:
    - TARGET="test"
  - rvm: 2.7.0
    env:
    - TARGET="test"
  - rvm: ruby-head
    env:
    - TARGET="test"
  allow_failures:
  - rvm: ruby-head
    env:
    - TARGET="test"
  fast_finish: true
